/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id: '',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_WmIZPlE9G',
  aws_user_pools_web_client_id: '7q5vqcdd54mijq3irkjvslitgc',
  oauth: {
    domain: 'v2gconnect-app.auth.eu-central-1.amazoncognito.com',
    scope: ['email', 'openid', 'profile'],
    redirectSignIn:
      process.env.NODE_ENV === 'production' ? 'https:/v2gconnect.de/dashboard' : 'http://localhost:5173/dashboard',
    redirectSignOut:
      process.env.NODE_ENV === 'production' ? 'https:/v2gconnect.de/auth/login' : 'http://localhost:5173/auth/login',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
};
